simulation:
  num_scenes: 2
  seconds_per_scene: 1
  base_save_path: ./_out
  traffic:
    num_vehicles: 30
    num_pedestrians: 10
    safe_spawn: true
    car_lights_on: true
    seed: null
sensors:
- name: Camera_Front
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1500.0'
    image_size_y: '1500.0'
    fov: '90.0'
  transform:
    location:
      x: 0.4
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
  collect_bbox: true
- name: Camera_Back
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1500.0'
    image_size_y: '1500.0'
    fov: '90.0'
  transform:
    location:
      x: -1.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 180.0
      roll: 0.0
  collect_bbox: true
- name: Camera_FrontRight
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1500.0'
    image_size_y: '1500.0'
    fov: '120.0'
  transform:
    location:
      x: 0.4
      y: 0.3
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 45.0
      roll: 0.0
  collect_bbox: true
- name: Camera_BackLeft
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1500.0'
    image_size_y: '1500.0'
    fov: '120.0'
  transform:
    location:
      x: -0.3
      y: -0.5
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 225.0
      roll: 0.0
  collect_bbox: true
