simulation:
  num_scenes: 2
  ticks_per_scene: 20
  base_save_path: "./_out"  
  traffic:
    num_vehicles: 30
    num_pedestrians: 10
    safe_spawn: true 
    car_lights_on: true
    seed: null  
sensors:
  - name: "camera_1"
    type: "camera"
    blueprint: "sensor.camera.rgb"
    attributes:
      image_size_x: "1280"
      image_size_y: "720"
      fov: "90"
    transform:
      location: {x: 0, y: 0, z: 2.4}
      rotation: {yaw: 0}
    collect_bbox: true 
  # - name: "camera_2"
  #   type: "camera"
  #   blueprint: "sensor.camera.rgb"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #     fov: "90"
  #   transform:
  #     location: {x: -1, y: 0, z: 2.4}
  #     rotation: {yaw: 180}
  #   collect_bbox: true
  # - name: "camera_3"
  #   type: "camera"
  #   blueprint: "sensor.camera.rgb"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: -0.5, z: 2.4}
  #     rotation: {yaw: 45}
  #   collect_bbox: true
  # - name: "camera_4"
  #   type: "camera"
  #   blueprint: "sensor.camera.rgb"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: 0.5, z: 2.4}
  #     rotation: {yaw: -45}
  #   collect_bbox: true
  # - name: "camera_5"
  #   type: "camera"
  #   blueprint: "sensor.camera.rgb"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: 0.5, z: 2.4}
  #     rotation: {yaw: -225}
  #   collect_bbox: true
  # - name: "camera_6"
  #   type: "camera"
  #   blueprint: "sensor.camera.rgb"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: -0.5, z: 2.4}
  #     rotation: {yaw: 225}
  #   collect_bbox: true
  # - name: "semantic_segmentation"
  #   type: "camera"
  #   blueprint: "sensor.camera.semantic_segmentation"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: 0, z: 2.4}
  #     rotation: {yaw: 0}
  # - name: "instance_segmentation"
  #   type: "camera"
  #   blueprint: "sensor.camera.instance_segmentation"
  #   attributes:
  #     image_size_x: "1280"
  #     image_size_y: "720"
  #   transform:
  #     location: {x: 0, y: 0, z: 2.4}
  #     rotation: {yaw: 0}
  - name: "radar"
    type: "radar"
    blueprint: "sensor.other.radar"
    attributes:
      horizontal_fov: "90"
      vertical_fov: "10"
      points_per_second: "5000"
      range: "250"
    transform:
      location: {x: 3, y: 0, z: 2}
      rotation: {pitch: 5, yaw: 0, roll: 0}
  # - name: "lidar"
  #   type: "lidar"
  #   blueprint: "sensor.lidar.ray_cast"
  #   attributes:
  #     channels: "64"
  #     range: "100"
  #     points_per_second: "250000"
  #     rotation_frequency: "20"
  #   transform:
  #     location: {x: 0, y: 0, z: 2.4}
  #     rotation: {yaw: 90}
  - name: "semantic_lidar"
    type: "lidar"
    blueprint: "sensor.lidar.ray_cast_semantic"
    attributes:
      channels: "64"
      range: "100"
      points_per_second: "250000"
      rotation_frequency: "20"
      upper_fov: "10"
      lower_fov: "-30"
      horizontal_fov: "360"
    transform:
      location: {x: 0, y: 0, z: 2.4}
      rotation: {yaw: 90}
  - name: "gnss"
    type: "gnss"
    blueprint: "sensor.other.gnss"
    attributes:
      noise_alt_bias: "0.0"
      noise_alt_stddev: "0.1"
      noise_lat_bias: "0.0"
      noise_lat_stddev: "0.1"
      noise_lon_bias: "0.0"
      noise_lon_stddev: "0.1"
    transform:
      location: {x: 0, y: 0, z: 2.4}  
      rotation: {yaw: 0, pitch: 0, roll: 0}
  - name: "imu"
    type: "imu"
    blueprint: "sensor.other.imu"
    attributes:
      noise_accel_stddev_x: "0.1"
      noise_accel_stddev_y: "0.1"
      noise_accel_stddev_z: "0.1"
      noise_gyro_stddev_x: "0.1"
      noise_gyro_stddev_y: "0.1"
      noise_gyro_stddev_z: "0.1"
      noise_gyro_bias_x: "0.0"
      noise_gyro_bias_y: "0.0"
      noise_gyro_bias_z: "0.0"
    transform:
      location: {x: 0, y: 0, z: 0}
      rotation: {yaw: 0, pitch: 0, roll: 0}