simulation:
  num_scenes: 1
  ticks_per_scene: 20
  base_save_path: ./_out
  traffic:
    num_vehicles: 30
    num_pedestrians: 10
    safe_spawn: true
    car_lights_on: true
    seed: null
sensors:
- name: camera
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1280'
    image_size_y: '720'
    fov: '90'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 24.0
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
  collect_bbox: true
