simulation:
  num_scenes: 2
  ticks_per_scene: 20
  base_save_path: ./_out
  traffic:
    num_vehicles: 30
    num_pedestrians: 10
    safe_spawn: true
    car_lights_on: true
    seed: null
sensors:
- name: Camera_Front
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 1.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
  collect_bbox: true
- name: Camera_Back
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: -1.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 180.0
      roll: 0.0
  collect_bbox: true
- name: Camera_FrontRight
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 1.0
      y: -0.5
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 45.0
      roll: 0.0
  collect_bbox: true
- name: Camera_FrontLeft
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 1.0
      y: 0.5
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: -45.0
      roll: 0.0
  collect_bbox: true
- name: Camera_BackRight
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 0.0
      y: 0.5
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: -225.0
      roll: 0.0
  collect_bbox: true
- name: Camera_BackLeft
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 0.0
      y: -0.5
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 225.0
      roll: 0.0
  collect_bbox: true
- name: Radar_Front
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: 3.0
      y: 0.0
      z: 1.5
    rotation:
      pitch: 5.0
      yaw: 0.0
      roll: 0.0
- name: Radar_FrontRight
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: 2.0
      y: -0.5
      z: 1.5
    rotation:
      pitch: 5.0
      yaw: 90.0
      roll: 0.0
- name: Radar_FrontLeft
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: 2.0
      y: 0.5
      z: 1.5
    rotation:
      pitch: 5.0
      yaw: -90.0
      roll: 0.0
- name: Radar_BackLeft
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: -1.5
      y: 0.5
      z: 1.5
    rotation:
      pitch: 5.0
      yaw: 180.0
      roll: 0.0
- name: Radar_BackRight
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: -1.5
      y: -0.5
      z: 1.5
    rotation:
      pitch: 5.0
      yaw: 180.0
      roll: 0.0
- name: Lidar
  type: lidar
  blueprint: sensor.lidar.ray_cast
  attributes:
    channels: '64.0'
    range: '100.0'
    points_per_second: '250000.0'
    rotation_frequency: '20.0'
    upper_fov: '10.0'
    lower_fov: '-30.0'
    horizontal_fov: '360.0'
    atmosphere_attenuation_rate: '0.004'
    dropoff_general_rate: '0.45'
    dropoff_intensity_limit: '0.8'
    dropoff_zero_intensity: '0.4'
    noise_stddev: '0.0'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 90.0
      roll: 0.0
- name: Semantic_Lidar
  type: semantic_lidar
  blueprint: sensor.lidar.ray_cast_semantic
  attributes:
    channels: '64'
    range: '100'
    points_per_second: '250000'
    rotation_frequency: '20'
    upper_fov: '10'
    lower_fov: '-30'
    horizontal_fov: '360'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 90.0
      roll: 0.0
- name: GNSS
  type: gnss
  blueprint: sensor.other.gnss
  attributes:
    noise_alt_bias: '0.0'
    noise_alt_stddev: '0.1'
    noise_lat_bias: '0.0'
    noise_lat_stddev: '0.1'
    noise_lon_bias: '0.0'
    noise_lon_stddev: '0.1'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
- name: IMU
  type: imu
  blueprint: sensor.other.imu
  attributes:
    noise_accel_stddev_x: '0.1'
    noise_accel_stddev_y: '0.1'
    noise_accel_stddev_z: '0.1'
    noise_gyro_stddev_x: '0.1'
    noise_gyro_stddev_y: '0.1'
    noise_gyro_stddev_z: '0.1'
    noise_gyro_bias_x: '0.0'
    noise_gyro_bias_y: '0.0'
    noise_gyro_bias_z: '0.0'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
- name: new_sensor_15
  type: instance_camera
  blueprint: sensor.camera.instance_segmentation
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
- name: new_sensor_16
  type: semantic_camera
  blueprint: sensor.camera.semantic_segmentation
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
