simulation:
  num_scenes: 2
  ticks_per_scene: 20
  base_save_path: ./_out
  traffic:
    num_vehicles: 30
    num_pedestrians: 10
    safe_spawn: true
    car_lights_on: true
    seed: null
sensors:
- name: camera_1
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1280'
    image_size_y: '720'
    fov: '90'
  transform:
    location:
      x: 1.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
  collect_bbox: true
- name: camera_2
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '1280'
    image_size_y: '720'
    fov: '90'
  transform:
    location:
      x: -1.0
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 180.0
      roll: 0.0
  collect_bbox: true
- name: radar
  type: radar
  blueprint: sensor.other.radar
  attributes:
    horizontal_fov: '90'
    vertical_fov: '10'
    points_per_second: '5000'
    range: '250'
  transform:
    location:
      x: 0.0
      y: 0.0
      z: 24.0
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
