simulation:
  num_scenes: 2
  seconds_per_scene: 3
  base_save_path: ./_out
  traffic:
    num_vehicles: 50
    num_pedestrians: 10
    safe_spawn: true
    car_lights_on: true
    seed: null
sensors:
- name: Camera_Front
  type: camera
  blueprint: sensor.camera.rgb
  attributes:
    image_size_x: '800.0'
    image_size_y: '600.0'
    fov: '90.0'
  transform:
    location:
      x: 0.4
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 0.0
      roll: 0.0
  collect_bbox: true
- name: Semantic_Lidar
  type: semantic_lidar
  blueprint: sensor.lidar.ray_cast_semantic
  attributes:
    channels: '64'
    range: '100'
    points_per_second: '250000'
    rotation_frequency: '20'
    upper_fov: '10'
    lower_fov: '-30'
    horizontal_fov: '360'
  transform:
    location:
      x: -0.3
      y: 0.0
      z: 2.4
    rotation:
      pitch: 0.0
      yaw: 90.0
      roll: 0.0
